source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'lorem_ipsum_amet'
gem 'faker'
gem 'sinatra-flash'
gem 'sinatra-reloader'
gem 'sinatra-contrib'
